module.exports = {
  peerConnected: "PEER_CONNECTED",
  peerDisconnected: "PEER_DISCONNECTED",
  sessionEstablish: "ESTABLISH_SESSION",
  userRegister: "USER_REGISTER",
  error: "ERROR",
  requireGame: "REQUIRE_GAME",
  login: "LOGIN",
  logout: "LOGOUT",
  loginSuccess: "LOGIN_SUCCESS",
  loginFail: "LOGIN_FAIL",
  handshake: "HANDSHAKE",
  handshakeAccepted: "HANDSHAKE_ACCEPTED",
  handshakeRejected: "HANDSHAKE_REJECTED",
  unauthorized: "UNAUTHORIZED",
};
